name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm install
    - run: npm test
    - uses: actions/cache@v3
      with:
        path: fuzzing/corpus
        key: fuzzing
    - run: npm run fuzz
